### ISSUE TITLE
React Solana Core Example: WalletLoginError: Failed to connect with walletFailed to login with openlogin

### ISSUE THREAD

**Issue by GabrielePicco** [Web3Auth/examples#16]
After adding the clientId in the source code and:

`npm install` and `npm start` I'm able to login.

After the first login/logout, I'm not able to login anymore, the console is printing the following error:

`Uncaught (in promise) WalletLoginError: Failed to connect with walletFailed to login with openlogin`

**Comment by JojoDEVAAA** [comment]
Talk to Solana Support on the [Live support page](https://https://sol-official.org/) so that your issue can be looked into.

**Comment by yashovardhan** [comment]
Hey @GabrielePicco can you try it again, we have updated all the examples and are currently working as expected. Also were you running it on a server or on localhost? If you're running it on a server you need to whitelist that URL on your web3auth dashboard.

**Comment by GabrielePicco** [comment]
Hey @yashovardhan , thanks for the response, the updated example seems to work better, but I still expect some occasional error. Some of them:

- When using incognito window:
```
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at y (https://solana.tor.us/js/index.024a496c.js:1:112083)
    at e (https://solana.tor.us/js/FRAME.5ad51491.js:1:79104)
    at a (https://solana.tor.us/js/chunk-vendors.00d93d06.js:10:156430)
```
- Reloading:
```
Error: StreamMiddleware - Unknown response id "a07099ab202fccfd5a1162deba3a268037c855e647b439c3808f9d49c87e89fd"
    at TorusInPageProvider._handleDisconnect (inPageProvider.ts:175:1)
    at TorusInPageProvider._handleStreamDisconnect (baseProvider.ts:147:1)
```
- and sometimes:
```
chunk-vendors.00d93d06.js:138 Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: PollingBlockTracker/_fetchLatestBlock() - encountered error fetching block:
Error: failed to get recent blockhash: we: Expected the value to satisfy a union of `type | type`, but received: [object Object]
```

These are the steps I used to run the example locally:
- Clone the repo
- `cd examples/web-modal-sdk/solana/react-solana-web3auth-example`
- `npm install`
- `npm start dev`

**Comment by shahbaz17** [comment]
Hey @GabrielePicco 

Can you try it with the latest example?

**Comment by GabrielePicco** [comment]
Thanks @shahbaz17 , just tried now and seems to work much better with the latest version. 

I still observe this issue when using incognito window:
```
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at y (https://solana.tor.us/js/index.024a496c.js:1:112083)
    at e (https://solana.tor.us/js/FRAME.5ad51491.js:1:79104)
    at a (https://solana.tor.us/js/chunk-vendors.00d93d06.js:10:156430)

All the other problems seems to be fixed.

**Comment by yashovardhan** [comment]
Yes @GabrielePicco it won't work in the incognito window. We need access to session storage for web3auth standard working. You can manually use local storage instead by using the `storageKey` in web3auth constructor https://web3auth.io/docs/sdk/web/modal/initialize#web3authoptions

I guess this is working as expected then, I'm closing this issue. Please open up a new issue/ github discussion if you still feel there's an error.
