### ISSUE TITLE
Error When building nextjs-solana-web3auth-example

### ISSUE THREAD

**Issue by bamdadam** [Web3Auth/examples#8]
### Detail
unable to build the project
### To Reproduce
`npm run build`
### Expected behavior
project building normaly
### Screenshots
![image](https://user-images.githubusercontent.com/78018383/188873681-0419c768-7a90-446b-a3c7-8a476113a496.png)
![image](https://user-images.githubusercontent.com/78018383/188873736-30c7beac-1390-42d6-9d88-becb21458b52.png)

**Comment by yashovardhan** [comment]
Hey @bamdadam 

Can you try once again, we have fixed the issues in next app
